version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mlflow_root_password
      MYSQL_DATABASE: mlflow_db
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio_access_key
      - AWS_SECRET_ACCESS_KEY=minio_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - minio
  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
  inference-api:
    build:
      context: ./inference
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  streamlit-gui:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8503:8503"
volumes:
  mysql_data:
  minio_data:
